#!/bin/bash

if [[ "$DOCKER_TAG" =~ "64" ]]; then
    export ARCH=x86_64 ARCH_TAG=64
else
    export ARCH=x86
fi
docker build --build-arg ARCH=$ARCH --build-arg ARCH_TAG=$ARCH_TAG -f $DOCKERFILE_PATH -t $IMAGE_NAME .